name: Notify commit to external repo

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    react:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "${{ toJSON(github) }}"
            - uses: actions/github-script@v6
              with:
                github-token: ${{ secrets.MY_TOKEN }}
                result-encoding: string
                script: |
                    await github.rest.actions.createWorkflowDispatch({
                        owner: 'gastonfournier',
                        repo: 'commit-reactor',
                        workflow_id: 'react.yaml',
                        ref: 'main',
                        inputs: {

                        }
                    })